name: ZeanonUtils
version: 1.2.0
api-version: 1.14
authors: [Zeanon, JavaFactoryDev]
main: de.zeanon.zeanonutils.ZeanonUtils
softdepend: [PlugMan]
commands:
  playerheads:
    description: Get yourself a player head
    aliases: [ph, playerhead]