name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Zeanon
main: de.zeanon.zeanonutils.ZeanonUtils
api-version: 1.15
softdepend: [ PlugMan ]
commands:
  playerheads:
    description: Get yourself a player head
    aliases: [ ph, playerhead ]
  zeanonutils:
    description: Basic command
    aliases: [ utils ]